---
- name: "Preflight - Fail if target host is not stable for this Role."
  fail:
    msg: "This role is not stable for the target operating system, {{ ansible_distribution }} {{ ansible_distribution_major_version }}."
  when: (ansible_distribution is not defined) or
        (ansible_distribution_version is not defined) or
        (ansible_distribution+" "+ansible_distribution_major_version not in certbot_stable_os)

- name: "Configure APT to use a PPA on Ubuntu."
  apt_repository:
    repo: "{{ item }}"
    state: present
    update_cache: 'yes'
  with_items: "{{ certbot_ppa }}"
  when: ansible_distribution == "Ubuntu"

- name: "Force APT Cache Update."
  apt:
    update_cache: 'yes'
    cache_valid_time: 0
  when: ansible_pkg_mgr == "apt"

- name: "Install Certbot Package."
  package:
    name: "{{ certbot_package }}"
    state: present

- name: "Configure Renewal Cronjob for Apache2."
  cron:
    name: "Automatically renew all certificates issued via certbot with Apache2."
    job: '"$(command -v certbot)" renew --post-hook "systemctl reload {{ webserver_apache_name }}" -n --user-agent "" --agree-tos --expand'
    state: present
    disabled: 'no'
    minute: '13'
    hour: '15'
    day: '*/3'
    weekday: '*'
    month: '*'
  when: webserver_name == "apache"

- name: "Configure Renewal Cronjob for NGINX."
  cron:
    name: "Automatically renew all certificates issued via certbot with NGINX."
    job: '"$(command -v certbot)" renew --post-hook "systemctl reload {{ webserver_nginx_name }}" -n --user-agent "" --agree-tos --expand'
    state: present
    disabled: 'no'
    minute: '15'
    hour: '13'
    day: '*/3'
    weekday: '*'
    month: '*'
  when: webserver_name == "nginx"

- name: "Get certificates using apache module against the staging server."
  command: certbot "{{ certbot_mode }}" -n --"{{ certbot_module }}" -d "{{ certbot_domains }}" -m "{{ certbot_email }}" --user-agent "" --agree-tos --expand --staging
  when: certbot_staging
  register: certbot_validation
  notify: "restart webserver {{ certbot_module }}"

- name: "Certbot output for staging."
  debug: msg="{{certbot_validation.stdout_lines}}"
  when: certbot_validation.stdout_lines is defined

- name: "Get certificates using apache module against the productive server."
  command: certbot "{{ certbot_mode }}" -n --"{{ certbot_module }}" -d "{{ certbot_domains }}" -m "{{ certbot_email }}" --user-agent "" --agree-tos --expand
  when: not certbot_staging
  register: certbot_validation
  notify: "restart webserver {{ certbot_module }}"
  ignore_errors: 'yes'

- name: "Certbot output for production."
  debug: msg="{{certbot_validation.stdout_lines}}"
  when: certbot_validation.stdout_lines is defined

- name: "Get certificates using apache module against the productive server enforcing a renewal."
  command: certbot "{{ certbot_mode }}" -n --"{{ certbot_module }}" -d "{{ certbot_domains }}" -m "{{ certbot_email }}" --user-agent "" --agree-tos --expand --force-renew
  when: not certbot_staging and certbot_force_renewal
  register: certbot_validation
  notify: "restart webserver {{ certbot_module }}"

- name: "Certbot output for production enforcing a renewal."
  debug: msg="{{ certbot_validation.stdout_lines }}"
  when: certbot_validation.stdout_lines is defined
